export { default as Home } from './Home';
export { default as Mypage } from './Mypage';
export { default as CookSiIn } from './CookSiIn';
export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
export { default as SetUp } from './SetUp';
export { default as Post } from './Post';
export { default as MyPost } from './MyPost';
export { default as Write } from './Write';
